on: 
  workflow_dispatch:
  
env:
  KUBCONFIG: ${{ secrets.KUBE_CONFIG }}

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
   
    - run: |
        
        export KUBECONFIG=$KUBCONFIG
        kubectl get po -A